#!/usr/bin/env node
// Derives the C06 operation catalogue (method, path, security, idempotency) from the
// Gateway-facing OpenAPI contracts in dlc-docs. Usage:
//   node scripts/generate-catalog.mjs <dlc-docs>/07-api/contracts/openapi <revision>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [dir, revision = 'unknown'] = process.argv.slice(2);
const read = (file) =>
  readFileSync(join(dir, file), 'utf8').replace(/\r\n/g, '\n');
const gateway = read('api-gateway.yaml');
const exposed = [
  ...gateway.matchAll(/^ {2}(\/\S+):\n {4}\$ref: \.\/([\w-]+\.yaml)#/gm),
];

const operations = [];
const cache = new Map();
for (const [, path, file] of exposed) {
  if (!cache.has(file)) cache.set(file, read(file));
  const text = cache.get(file);
  const start = text.indexOf(`\n  ${path}:\n`);
  if (start < 0) throw new Error(`${path} not found in ${file}`);
  const rest = text.slice(start + 1);
  const end = rest.slice(1).search(/^ {2}\/|^\S/m);
  const block = end < 0 ? rest : rest.slice(0, end + 1);
  for (const m of block.matchAll(
    /^ {4}(get|post|put|patch|delete):\n([\s\S]*?)(?=^ {4}(?:get|post|put|patch|delete):|(?![\s\S]))/gm,
  )) {
    const body = m[2];
    operations.push({
      operationId: body.match(/operationId: (\S+)/)?.[1] ?? '',
      method: m[1].toUpperCase(),
      path: `/api/v1${path}`,
      public: /^ {6}security: \[\]/m.test(body),
      idempotent: /parameters\/IdempotencyKey/.test(body),
    });
  }
}
const out = `// Generated by scripts/generate-catalog.mjs from dlc-docs ${revision}
// (07-api/contracts/openapi/api-gateway.yaml and its owner contracts). Do not edit.
export const CATALOG_REVISION = '${revision}';
export const OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;
`;
writeFileSync('src/core/http/__generated__/catalog.ts', out);
console.log(
  `catalog: ${operations.length} operations from ${exposed.length} paths`,
);
